### PR TITLE
Add docstring to map_parts.

### PR DESCRIPTION
**Pull request by fredrikekre**

### CODE REVIEW

**Comment by fverdugo** [comment]
Hi @fredrikekre thanks for opening this!

Could you instead document the generic method 

https://github.com/fverdugo/PartitionedArrays.jl/blob/b3eaa2ac84baccb791765d80a2f1fbc4be0d810e/src/Interfaces.jl#L86

with a similar docstring?

Once the generic function is documented, perhaps it is not needed to document each one of the particular implementations.

**Comment by fredrikekre** [comment]
Sure. I was moving this docstring back and forth between those places, but in the end wasn't sure it was generic enough. I will move it.

**Comment by fredrikekre** [comment]
Updated, but kept the examples using the MPI backend to make it more concrete.

**Comment by fverdugo** [comment]
> Updated, but kept the examples using the MPI backend to make it more concrete.

Sure, the example needs to consider a concrete implementation. That's fine.

**Comment by fverdugo** [comment]
Feel free to add more docstrings. The package is functional but still mostly undocumented.

**Comment by fredrikekre** [comment]
I am sure I will find other things to document as I discover the functionality. Slightly off topic, but where would be a good place to ask questions about the package?

**Comment by fverdugo** [comment]
>  Slightly off topic, but where would be a good place to ask questions about the package?

We can try:

https://github.com/fverdugo/PartitionedArrays.jl/discussions

**Pull request merged**
